# Generated by Django 6.0.6 on 2026-07-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهلت پرداخت'),
        ),
    ]
