# Generated by Django 6.0.6 on 2026-07-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_alter_invoice_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='factor_id',
            field=models.CharField(blank=True, max_length=34, null=True, unique=True, verbose_name='آیدی فاکتور'),
        ),
    ]
