# Generated by Django 6.0.6 on 2026-07-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_invoice_factor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='factor_image',
            field=models.ImageField(blank=True, null=True, upload_to='factor_image/', verbose_name='تصویر رسید پرداخت'),
        ),
    ]
