# Generated by Django 6.0.6 on 2026-07-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان هزینه')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ کل (تومان)')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'هزینه ساختمان',
                'verbose_name_plural': 'هزینه\u200cهای ساختمان',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=40, unique=True, verbose_name='نام مالک واحد')),
                ('unit_number', models.PositiveIntegerField(unique=True, verbose_name='شماره واحد')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره همراه مالک')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیدی تلگرام مالک')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحدها',
            },
        ),
    ]
