# Generated by Django 6.0.6 on 2026-07-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=40, verbose_name='نام مالک واحد'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.PositiveIntegerField(verbose_name='شماره واحد'),
        ),
    ]
