# Generated by Django 6.0.6 on 2026-07-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0002_alter_unit_unit_name_alter_unit_unit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildmanager',
            name='build_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='کد ساختمان'),
        ),
    ]
