# Generated by Django 6.0.6 on 2026-07-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0003_buildmanager_build_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildmanager',
            name='manager_id',
            field=models.CharField(blank=True, max_length=34, null=True, unique=True, verbose_name='آیدی مدیر'),
        ),
    ]
