# Generated by Django 6.0.6 on 2026-07-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building', '0004_buildmanager_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='آیدی واحد'),
        ),
    ]
